### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by imlinhanchao** [iamyy/wechat-spider#3]
跑了900多個就報下面的錯誤，多次嘗試均是如此。
`(node:16260) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token u in JSON at position 0`

另外`startDate`用來做什麽？

**Comment by iamyy** [comment]
@imlinhanchao startDate 是标明拉取文章的日期范围的，即拉取从 startDate 这一天起到当日为止这段时间内的文章。报错应该是某次解析 JSON 失败..

**Comment by fzy577** [comment]
可以获取阅读量、点赞数、发布日期吗

**Comment by iamyy** [comment]
目前不行。 @fzy577
